modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/DerkOttersberg/seamless-api/issues"

[[mods]]
modId="seamlessapi"
version="${mod_version}"
displayName="Seamless API"
displayURL="https://github.com/DerkOttersberg/seamless-api"
authors="Derk Ottersberg"
description='''Shared integration APIs for the Seamless mod family.'''

[[dependencies.seamlessapi]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.seamlessapi]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
