plugins {
    id 'dev.architectury.loom'
}

base {
    archivesName = rootProject.archives_base_name
}

dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()
    modImplementation libs.fabric.loader
}

sourceSets.main {
    java.srcDir rootProject.file('common/src/main/java')
    resources.srcDir rootProject.file('common/src/main/resources')
}

loom {
    mods {
        seamlessapi {
            sourceSet sourceSets.main
        }
    }
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

tasks.named('jar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "${rootProject.archives_base_name}-${project.version}-fabric-dev.jar"
}

tasks.named('remapJar') {
    archiveFileName = "${rootProject.archives_base_name}-${project.version}-fabric.jar"
}

tasks.named('sourcesJar', Jar) {
    from project(':common').sourceSets.main.allSource
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "${rootProject.archives_base_name}-${project.version}-fabric-sources.jar"
}

tasks.named('remapSourcesJar') { archiveFileName = "${rootProject.archives_base_name}-${project.version}-fabric-sources.jar" }
