plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

def replaceProperties = [
    mod_version: mod_version,
    loader_version_range: loader_version_range,
    forge_version_range: forge_version_range,
    minecraft_version_range: minecraft_version_range
]

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }

        register('client')
        register('server') {
            args '--nogui'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.5'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

tasks.withType(ProcessResources).configureEach {
    inputs.properties(replaceProperties)

    filesMatching('META-INF/mods.toml') {
        expand(replaceProperties)
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
            artifactId = project.archives_base_name
        }
    }
    repositories {
        mavenLocal()
    }
}
