modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "seamlessapi"
version = "1.0.0"
displayName = "SeamlessAPI"
description = '''
SeamlessAPI — shared library mod for Seamless systems.
Allows other mods to register food buffs, deconstruction hooks, and future integrations.
'''

[[dependencies.seamlessapi]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamlessapi]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
