modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "seamlessapi"
version = "${version}"
displayName = "SeamlessAPI"
description = '''
SeamlessAPI — shared library mod for Seamless systems.
Allows other mods to register food buffs, deconstruction hooks, and future integrations.
'''

[[dependencies.seamlessapi]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamlessapi]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
